// eslint-disable
describe('Solo Test', () => {
  it('Launches a game and quits it', () => {
    cy.visit('http://localhost:8080/#/');
    cy.contains('Welcome to a Stronger Tetris');
    cy.contains('Rooms:');
    cy.contains('Player Name').type('Player 1');
    cy.contains('Room Name').type('Player 1\'s Room');
    cy.contains('GO').click();
    cy.wait(100);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.wait(5000);
    cy.get(':nth-child(5) > .q-btn__content').click();
  });

  it('Launches a game and plays till end then quits', () => {
    cy.visit('http://localhost:8080/#/');
    cy.contains('Welcome to a Stronger Tetris');
    cy.contains('Rooms:');
    cy.contains('Player Name').type('Player 1');
    cy.contains('Room Name').type('Player 1\'s Room');
    cy.contains('GO').click();
    cy.wait(100);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.get(':nth-child(5) > .q-btn__content').click();
  });

  it('Launches a game and plays till end then restarts before quiting', () => {
    cy.visit('http://localhost:8080/#/');
    cy.contains('Welcome to a Stronger Tetris');
    cy.contains('Rooms:');
    cy.contains('Player Name').type('Player 1');
    cy.contains('Room Name').type('Player 1\'s Room');
    cy.contains('GO').click();
    cy.wait(200);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(2000);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get('.custom-area').type(' ');
    cy.wait(1000);
    cy.get(':nth-child(5) > .q-btn__content').click();
  });

  it('Launches a game and triggers all actions and quits', () => {
    cy.visit('http://localhost:8080/#/');
    cy.contains('Welcome to a Stronger Tetris');
    cy.contains('Rooms:');
    cy.contains('Player Name').type('Player 1');
    cy.contains('Room Name').type('Player 1\'s Room');
    cy.contains('GO').click();
    cy.wait(200);
    cy.get(':nth-child(2) > .q-btn__content > .block').click();
    cy.wait(2000);
    cy.get('.custom-area').click();
    cy.get('.custom-area').click();
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type(' ');
    cy.wait(2000);
    cy.get(':nth-child(3) > .q-toggle > .q-toggle__inner > .q-toggle__thumb').click();
    cy.get(':nth-child(4) > .q-toggle > .q-toggle__inner > .q-toggle__thumb').click();
    cy.get(':nth-child(3) > .q-btn__content > .q-icon').click();
    cy.get(':nth-child(4) > .q-btn__content > .q-icon').click();
    cy.wait(2000);
    cy.get(':nth-child(3) > .q-btn__content > .q-icon').click();
    cy.get('.custom-area').click();
    cy.get('.custom-area').click();
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type(' ');
    cy.get(':nth-child(4) > .q-btn__content > .q-icon').click();
    cy.get(':nth-child(3) > .q-toggle > .q-toggle__inner > .q-toggle__thumb').click();
    cy.get(':nth-child(4) > .q-toggle > .q-toggle__inner > .q-toggle__thumb').click();
    cy.get('.custom-area').click();
    cy.get('.custom-area').click();
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{upArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{downArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{leftArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type('{rightArrow}');
    cy.get('.custom-area').type(' ');
    cy.wait(2000);
    cy.get(':nth-child(5) > .q-btn__content').click();
  });
});
